#Exemple of a Docker compose that bind 3 docker to deploy the sate platform
#entrypoint: bash -c "for f in /var/lib/sate6_reports/*.xml; do xmllint --schema /var/lib/sate6-format.xsd "$f" | grep "validates"; done;"

version: '2'

services:
  sate:
    build: .
    container_name: sate
    ports:
      - 3000:80
    volumes:
      - ./src:/var/www/html
      - ./data/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./data/samate/SATE:/home/SATE
      - ./data/smarty-logs/:/home/tmp/
    env_file: .env

  mysql:
    image: mysql:5.5
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/samate/SATE/6/tools/association_suggestion/association_suggestions_plus.sql:/var/lib/association_suggestions_plus.sql
      - ./data/samate/SATE/6/tools/association_suggestion/id_check.sql:/var/lib/id_check.sql
    environment:
      - MYSQL_ROOT_PASSWORD=sate
    ports:
      - 4000:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 5000:80
    environment:
      - PMA_HOST=mysql

